### ISSUE TITLE
Errors...

### ISSUE THREAD

**Issue by ImInTheICU** [GarryyBD/versatools#12]
There's a-lot of problems like 
```
Failed: Error 'ascii' codec can't encode characters in position 76-78: ordinal not in range(128) while running send_friend_request. Tried 3 times #6
```
or when using capsolver you'll randomly receive
```
{"errorId":1,"errorCode":"ERROR_CAPTCHA_SOLVE_FAILED","errorDescription":"the current website is under maintenance, please visit later","taskId":"9d89c102-933d-4eab-be77-9186de4c6ebb","status":"failed"}

``` 
when creating cookies.
It also seems group-joining, follow-botting, game-botting also have problems.
Other then that pretty solid tool!

**Comment by astrajs** [comment]
Roblox had pushed an update that patched (or semi-patched) most of the captcha solvers (including capbypass). We just have to wait for the captcha solvers to fix itself in the upcoming few days. Hence why it wrote "under maintenace" there.

Common issue, not just versatools. other service providers including rblx-store is experiencing the same problem.

**Comment by GarryyBD** [comment]
First error i think its because you didn't delete versatools folder before downloading the new update (ik its akward, i will investigate how that happens)

Second error comes from the captcha solver which you are using that is under maintenance.

**Comment by luxkatana** [comment]
Had the same problem at first.. Solved it by using a new **virtualenv**
