### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by Aixory** [GarryyBD/versatools#13]
Hey Garry,
We just spoke and I wanted a little help in using the bot application, can you help me, please?

**Comment by GarryyBD** [comment]
You must generate cookies (bots) that will be used to follow you. For it, you can use our GeneratorTool

**Comment by Aixory** [comment]
> You must generate cookies (bots) that will be used to follow you. For it, you can use our GeneratorTool

What's Max Workers and Max Generations?

**Comment by Aixory** [comment]
What's the difference and what each one mean?

**Comment by GarryyBD** [comment]
Max workers is the amount of threads you want to allocate to the tool. The more you have, the faster it will be.

Max generations is the quantity you want the tool to generate

**Comment by Aixory** [comment]
Gotcha, basically how many cookies do I want to generate right?

**Comment by GarryyBD** [comment]
Yes

**Comment by Aixory** [comment]
Where do you recommend me to buy my proxies?

**Comment by Aixory** [comment]
also, incase I want 200k followers how many cookies do I have to generate 200k? so one cookie for one account?

**Comment by GarryyBD** [comment]
Im currently using pyproxy.com residential proxies. Make sure to buy static proxies and not rotating one

And yes, one cookie is one account. So you will need 200k cookies for 200k followers

**Comment by Aixory** [comment]
and how many proxies I need to buy in order to get 200k cookies?

**Comment by GarryyBD** [comment]
A lot. Maybe 100k is good. There's no absolute amount. Pyproxy on residential plan, offers an unlimited amount of proxies
