### ISSUE TITLE
Follow Bot [bug]

### ISSUE THREAD

**Issue by ImInTheICU** [GarryyBD/versatools#14]
Error's found while using FollowBot
```
Failed: {"errorId":1,"taskId":"5e374013-c86a-40e2-8a07-102f978410a4","solution":null}
Failed: CSRF TOKEN not found. Invalid cookie probably
Failed: argument should be a bytes-like object or ASCII string, not 'NoneType'
```
All of these happen randomly without any explanation `CSRF TOKEN` makes no sense because all my cookies are working.
Captcha error make's no sense because it works for everything else.

**Comment by GarryyBD** [comment]
Sometimes captcha solver works only on some public keys but sadly there's no way to know really if the error comes from capbypass or roblox changed their API. i have to check it out
