### ISSUE TITLE
[FIXED] Could not load data from external website

### ISSUE THREAD

**Issue by luxkatana** [GarryyBD/versatools#15]
Tried to use **Cookie Verifier**. It gave me this error
```
Verified: 0 | Failed: 2 | Total: 2
Failed: Error Could not load data from external website while running verify_cookie. Tried 3 times
```
I do have a valid proxy

**Comment by luxkatana** [comment]
![image](https://github.com/GarryyBD/versatools/assets/57036931/c3a986a9-23ca-4554-94bd-bf8c58cb9d0a)

**Comment by GarryyBD** [comment]
no idea, it happened to someone else too but it comes from your computer ..

**Comment by GarryyBD** [comment]
try using other proxies

**Comment by luxkatana** [comment]
Unfortunately that didn't fix the issue.

**Comment by GarryyBD** [comment]
I have few questions.

From your browser, are you able to access this website: https://api.mail.tm/domains ?

And does this error happen only on cookieverifier tool?

**Comment by luxkatana** [comment]
> I have few questions.
> 
> From your browser, are you able to access this website: https://api.mail.tm/domains ?
> 
> And does this error happen only on cookieverifier tool?

***And does this error happen only on cookieverifier tool?***
The ones that is requesting to roblox.com except the proxy checker, that one works.

*** From your browser, are you able to access this website: https://api.mail.tm/domains**
Yeah, I am able to access that website
![image](https://github.com/GarryyBD/versatools/assets/57036931/f3ec22e3-293d-45fe-838a-01da3dda5df7)

**Comment by GarryyBD** [comment]
weird, are you able to access that page?

https://[accountsettings.roblox.com/v1/email](https://accountsettings.roblox.com/v1/email)

**Comment by luxkatana** [comment]
Yeah
![image](https://github.com/GarryyBD/versatools/assets/57036931/7d440ab2-5452-4a92-95bc-2dd26e8f9fda)

**Comment by GarryyBD** [comment]
Something is blocking Versatools from making requests. Maybe your antivirus. You could try disabling it but I don't recommend, check if antivirus is actually flagging and restricting Versatools. Also you could try running Versatools from source

**Comment by luxkatana** [comment]
![image](https://github.com/GarryyBD/versatools/assets/57036931/2b05bc16-3be6-474c-9d48-c12d9fecd51d)
is it perhaps possible that roblox updated their system? I've ran it on a sandbox.

Does it work for you normally?

**Comment by GarryyBD** [comment]
Yes it works with me and other people. Error is specific to your environment and I have no idea where it comes from since I can't reproduce it..

**Comment by GarryyBD** [comment]
Hey,

I have fixed "Could not load data from external website" error

You can download update here: https://github.com/GarryyBD/versatools/releases/tag/v2.0.1
