### ISSUE TITLE
How to change path to run it with edge?

### ISSUE THREAD

**Issue by StupidProAArsenal** [GarryyBD/versatools#16]
is it possible to run with edge? microsoft edge is also built with chromium, so how can i change the path?

If not, could you add a support for edge? would appreciate it!

Issue:

![image](https://github.com/GarryyBD/versatools/assets/76736126/4a1a74ae-3879-4e51-9438-8b54b4e1ca6b)

**Comment by GarryyBD** [comment]
Can you download google chrome it will help

**Comment by StupidProAArsenal** [comment]
yeah okay

**Comment by StupidProAArsenal** [comment]
question, where to add proxies? and do free proxies work?
