### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by 0b9** [GarryyBD/versatools#18]
Works on Unfx proxy checker and other tools:
![image](https://github.com/GarryyBD/versatools/assets/101853918/3763e97a-80b1-4a34-ab1b-5726c023b640)

Not working on Versatools:
![image](https://github.com/GarryyBD/versatools/assets/101853918/b9e8d433-91d7-400d-a772-49e180fe749c)

**Comment by GarryyBD** [comment]
Not sure but may be related with #15
Does AssetsDownloader tool works for you?

**Comment by 0b9** [comment]
I figured it out, the VPN/Proxy I had on caused the problem. (I'm using proxifier for system wide proxy) 
Weird, since using proxies while my VPN is on works on other tools, just not this one. 🤷‍♂️

**Comment by 0b9** [comment]
After disabling my VPN, the proxy checker works, but every other tool doesn't work, this includes AssetDownloader and CookieVerifier. And yes, I can open the api page in my browser with no problems

**Comment by GarryyBD** [comment]
If you receive the "Could not load data from external website" error, please know that I'm actively investigating it. I haven't experienced this problem and all tools work for me and some people which is weird

**Comment by GarryyBD** [comment]
Hey,

I have fixed "Could not load data from external website" error

You can download update here: https://github.com/GarryyBD/versatools/releases/tag/v2.0.1
