### ISSUE TITLE
Failed: Error timed out while running get_csrf_token. Tried 3 times

### ISSUE THREAD

**Issue by 1ukyoo** [GarryyBD/versatools#19]
In cookies generator i got this error
![image](https://github.com/GarryyBD/versatools/assets/116929920/16bab4fe-0fbd-4c6a-86a7-ca037f90d256)

**Comment by GarryyBD** [comment]
I think it's because your proxies are flagged and roblox doesn't allow to get csrf_token

**Comment by 1ukyoo** [comment]
i have to add funds to capbypass?

**Comment by 1ukyoo** [comment]
i tried checking my cookies and i got this now...
![image](https://github.com/GarryyBD/versatools/assets/116929920/4324f847-a68a-4cc2-bb46-0133c16e168e)

**Comment by GarryyBD** [comment]
Yes, Capbypass is a paid funcaptcha solver service. It costs around 1$ to solve 1k funcaptchas.

**Comment by GarryyBD** [comment]
Make sure to use Europe proxies because roblox locks cookies on regions

**Comment by luxkatana** [comment]
> Yes, Capbypass is a paid funcaptcha solver service. It costs around 1$ to solve 1k funcaptchas. 

If I don't pay, which options can I then not use?

**Comment by GarryyBD** [comment]
> > Yes, Capbypass is a paid funcaptcha solver service. It costs around 1$ to solve 1k funcaptchas.
> 
> If I don't pay, which options can I then not use?

I don't know of any other alternatives to capbypass. other solvers are not able to solve funcaptchas

**Comment by luxkatana** [comment]
> > > Yes, Capbypass is a paid funcaptcha solver service. It costs around 1$ to solve 1k funcaptchas.
> > 
> > 
> > If I don't pay, which options can I then not use?
> 
> I don't know of any other alternatives to capbypass. other solvers are not able to solve funcaptchas

I meant for example if I don't have any credits over (or I just don't want to pay for capbypass' credits) what options or features of **versatools** can I then not use?

**Comment by GarryyBD** [comment]
> > > > Yes, Capbypass is a paid funcaptcha solver service. It costs around 1$ to solve 1k funcaptchas.
> > > 
> > > 
> > > If I don't pay, which options can I then not use?
> > 
> > 
> > I don't know of any other alternatives to capbypass. other solvers are not able to solve funcaptchas
> 
> I meant for example if I don't have any credits over (or I just don't want to pay for capbypass' credits) what options or features of **versatools** can I then not use?

Cookie generator, follow bot, group join bot and comment bot
