### ISSUE TITLE
making cookies gen unflagged

### ISSUE THREAD

**Issue by GarryyBD** [GarryyBD/versatools#26]

**Comment by maxhithere** [comment]
i made an unflagged cookie gen. unless ur very experienced with the api u won't succeed in making it. it involves lots of undocumented and hidden apis to fully make it unflagged.

best of luck

**Comment by GarryyBD** [comment]
> i made an unflagged cookie gen. unless ur very experienced with the api u won't succeed in making it. it involves lots of undocumented and hidden apis to fully make it unflagged.
> 
> best of luck

I wonder how you did it if what you say makes absolutely no sense. There's nothing such as hidden apis

**Comment by maxhithere** [comment]
hidden as in not documented and not publicly known

**Comment by GarryyBD** [comment]
ok i thought to you meant hidden to the browser. then you probably have tried many random apis to find which one/ones make cookies unflagged.
