### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by charliebrassington** [GarryyBD/versatools#32]
- Maybe [this](https://github.com/GarryyBD/versatools/blob/main/src/App.py#L105) should be refactored into its own separate class or smaller funcs to follow SRP in SOLID.
- Should also think about changing from sync to async for HTTP(s) requests seeing as the is a huge performance increase and can finally start reaching versatile in speed.

**Comment by GarryyBD** [comment]
- I appreciate the suggestion to refactor into a separate class or smaller functions to adhere to the SRP in SOLID. While I agree that modularizing the code can enhance maintainability, for this specific isolated section, the current implementation seems sufficient and straightforward. I'll keep this in mind for larger-scale modifications.

- Regarding the transition from synchronous to asynchronous HTTP(s) requests, I understand the potential performance benefits it can offer. However, in the context of our project, where requests need to be executed sequentially, the advantages of asynchronous operations might not be fully realized. Asynchronous programming is more beneficial when parallel execution can be leveraged, such as fetching data from a database concurrently. I'll certainly keep an eye on future requirements that may warrant reconsideration of this design choice.
