### ISSUE TITLE
Failed: Error 'ascii' codec can't encode characters in position 76-78: ordinal not in range(128) while running send_friend_request. Tried 3 times

### ISSUE THREAD

**Issue by luxkatana** [GarryyBD/versatools#6]
I tried to **Friend request Bot**. Didn't work raised an error.

**Comment by GarryyBD** [comment]
Hey,

To help others encountering this issue, may I know how you fixed it ?

**Comment by luxkatana** [comment]
👋 I don't know how the error ended but I made a new **virtualenv** and after that it worked. I think some packages in my main python-environment may be corrupted but for now. It's solved.

**Comment by GarryyBD** [comment]
thanks
